version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: bla_api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
    - DB_HOST
    - DB_PASSWORD
    - DB_USERNAME
    - DB_SCHEMA
    - DB_NAME